services:
  - type: web
    name: tds-proration-api
    runtime: python
    plan: free
    rootDir: proration_api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
